services:
  telegram-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-scraper
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - tgcrawler-network
    volumes:
      - ${DATA_DIR}/data:/app/data
      - ${DATA_DIR}/logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
      - TZ=Europe/Moscow
      - PLAYWRIGHT_EXECUTABLE_PATH=/usr/bin/chromium-browser
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - START_ON_BOOT=true
      - START_ON_BOOT_DELAY_MS=10000
      - START_ON_BOOT_ATTEMPTS=5
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s


  postgres:
    image: postgres:18
    container_name: tgcrawler-postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ${DATA_DIR}/pg:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tgcrawler-network


  nocodb:
    image: nocodb/nocodb:latest
    ports:
      - "8080:8080"
    environment:
      - NC_DB=pg://postgres:5432?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}&d=${POSTGRES_DB}‚Äù
    volumes:
      - ${DATA_DIR}/nocodb:/usr/app/data
    restart: unless-stopped
    depends_on: 
       - postgres
    networks:
      - tgcrawler-network


  caddy:
    image: caddy:2-alpine
    container_name: tgcrawler-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ${DATA_DIR}/caddy/data:/data
      - ${DATA_DIR}/caddy/config:/config
    environment:
      - ACME_AGREE=true
    depends_on:
      - telegram-scraper
    networks:
      - tgcrawler-network



networks:
  tgcrawler-network:
    driver: bridge